name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: List Files (كشف مكان الملفات)
        run: |
          echo "محتويات المجلد الحالي:"
          ls -R
          
      - name: Install and Build
        run: |
          npm install
          npm run build
